name = "readsthis"
compatibility_date = "2024-04-10"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "readsthis"
database_id = "16ee1e25-a486-4ef7-98bd-04022f077718"

[assets]
directory = "./assets"
binding = "ASSETS"

[[unsafe.bindings]]
name = "API_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 100, period = 60 }

[[unsafe.bindings]]
name = "SHARE_API_RATE_LIMITER"
type = "ratelimit"
namespace_id = "1002"
simple = { limit = 1, period = 60 }

# Cron trigger to run the nightly Readwise sync at 02:00 UTC every day
# Run the batch sync every hour on the hour
[triggers]
crons = ["0 * * * *"]
